<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseProject_InventoryManagement.Contracts\CourseProject_InventoryManagement.Contracts.csproj" />
    <ProjectReference Include="..\CourseProject_InventoryManagement.Domain\CourseProject_InventoryManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\CQRS\Commands\GeneralCommands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Ardalis.Result.AspNetCore" Version="10.1.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
  </ItemGroup>

</Project>
